### ISSUE TITLE
i/o Timeout to _bulk

### ISSUE THREAD

**Issue by thadamski** [abutaha/aws-es-proxy#41]
Hi, I'm receiving an `i/o timeout` and then a container crash/restart when attempting to use the `aws-es-proxy` container in my EKS deployment (v1.11.5). I have a fluent-bit configuration pointing to the `aws-es-proxy` service (defined in the yaml below). Any idea on why I would be receiving the timeout? Perhaps you can see an obvious misconfiguration... Thank you in advance for any help you may provide!

### Output
```
2018/12/19 07:46:52 Listening on 0.0.0.0:9200...
2018/12/19 07:46:55 Generated fresh AWS Credentials object
2018/12/19 07:47:25 Post https://vpc-xxxxxxxxxxxxx-abcdefghijklmnopqrstuvwxyz.us-east-1.es.amazonaws.com/_bulk: dial tcp 10.1.2.3:443: i/o timeout
```

### AWS ES Proxy Service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: aws-es-proxy
  namespace: logging
  labels:
    app: aws-es-proxy
spec:
  ports:
    - port: 9200
      name: aws-es-proxy
  selector:
    app: aws-es-proxy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-es-proxy
  namespace: logging
  labels:
    app: aws-es-proxy
spec:
  selector:
    matchLabels:
      app: aws-es-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-es-proxy
    spec:
      volumes:
      - name: varlog
        emptyDir: {}
      containers:
      - image: abutaha/aws-es-proxy:0.9
        name: aws-es-proxy
        args:
          - -listen=0.0.0.0:9200
          - -endpoint=https://vpc-xxxxxxxxxxxxx-abcdefghijklmnopqrstuvwxyz.us-east-1.es.amazonaws.com
          - -verbose
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "xxxxxxxxxxxxxxxxx"
        - name: AWS_SECRET_ACCESS_KEY
          value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ports:
          - containerPort: 9200
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "1G"
```

### Fluent Bit DS
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.14.9
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "aws-es-proxy"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```
